#!/bin/bash

set -e

NAME=Sia

. $(dirname "$0")/docker.bash

start() {
  docker run --rm -d --name $NAME \
    --publish 127.0.0.1:9980:9980 \
    nebulouslabs/siaantfarm

    echo type=sia
    echo endpoint=http://$(docker_ip):9980/
    echo _connect=$(docker_ip):9980
}

. $(dirname "$0")/run.bash
